version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.1
jobs:
  build:
    docker:
      - image: maven:3.6.3-jdk-8
    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: mvn clean install

      -  persist_to_workspace:
          root: . 
          paths: 
            - target/

  build_docker_image:
    docker:
      - image: docker:20.10.14
    working_directory: /app

    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build Docker Image
          command: |
            docker build -t my-java-image .
      - store_artifacts:
          path: my-java-app
      # - run:
      #     name: Deploy to Google Cloud Platform
      #     command: |
      #       echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
      #       gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      #       gcloud --quiet config set project $GCP_PROJECT_ID
      #       gcloud --quiet config set container/use_client_certificate True
      #       gcloud --quiet config set compute/zone $GCP_COMPUTE_ZONE
      #       gcloud --quiet container clusters get-credentials $GCP_CLUSTER_NAME
      #       kubectl config use-context gke_$GCP_PROJECT_ID_$GCP_COMPUTE_ZONE_$GCP_CLUSTER_NAME
      #       kubectl set image deployment/$GCP_DEPLOYMENT_NAME $GCP_CONTAINER_NAME=$DOCKER_USERNAME/my-java-image:$CIRCLE_SHA1
  gcr-push:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - gcp-gcr/push-image:
          registry-url: asia-docker.pkg.dev/sej-store-cloud-dev/ane-1-sc-art-reg-dev-24
          tag: latest
          image: my-java-image
          google-project-id: ORB_ENV_PROJECT_ID
workflows:
  mvn-docker-build-workflow:
    jobs:
      - build
      - build_docker_image:
          requires:
            - build
      - gcr-push:
          requires:
              - build_docker_image